# Generated by Django 5.2.5 on 2025-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherrequest',
            old_name='location',
            new_name='location_input',
        ),
        migrations.RemoveField(
            model_name='weatherrequest',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='weatherrequest',
            name='weather_data',
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='normalized_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='source',
            field=models.CharField(choices=[('city', 'City/Town'), ('zip', 'Zip/Postal'), ('coords', 'Coordinates'), ('landmark', 'Landmark/Fuzzy')], default='city', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='weather_current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='weather_forecast',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
